MONGO_DB_HOST = "0.0.0.0"
MONGO_DB_PORT = 27017
MONGO_DB_NAME = "observations"
MONGO_DB_USER_NAME = ""
MONGO_DB_PASSWORD = ""
MONGO_DB_STATS_COLLECTION = "CLIMATE_STATS"
# location where the sensor is
SENSOR_LOCATION = "home"
